import Head from 'next/head'
// import { Inter } from '@next/font/google'
import { NextPage } from 'next'
import WithSubnavigation from '@/components/NavBar/NavBar';
import Hero from '@/components/Hero/Hero';
import Form from '@/components/Form/Form';

// const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <WithSubnavigation /> */}
            <Hero />
            <Form />
        </>
    )
}

export default Home;